// Generated by PJSX. Native imports keep their authored relative paths.
const std = @import("std");
const rt = @import("compiled_runtime");
const V = rt.Value;
pub fn render(w: *std.Io.Writer, arena: std.mem.Allocator, ctx: anytype, props: V, instance_id: []const u8) !void {
_ = &ctx; _ = &instance_id; try rt.validate(props);
const v1: V = try rt.get(props, "rows"); _ = &v1;
const v2: V = try rt.indexed(arena, try rt.get(props, "rows"), V{ .float = 0 }); _ = &v2;
const v3: V = V{ .float = 0 }; _ = &v3;
const v4: V = V{ .string = "" }; _ = &v4;
const v5: V = v7: { var results: std.array_list.Managed(V) = .init(arena); for (try rt.items(v1)) |v6| { if (rt.truthy(try rt.stringMethod(arena, "includes", try rt.stringMethod(arena, "toLowerCase", try rt.get(v6, "name"), &.{}), &.{try rt.stringMethod(arena, "toLowerCase", v4, &.{})}))) try results.append(v6); } break :v7 V{ .array = results }; }; _ = &v5;
const initial_values = try rt.object(arena, &.{"user"}, &.{v2});
const initial_cache = try rt.object(arena, &.{}, &.{});
const initial_seed = try rt.componentSeed(arena, initial_values, props, initial_cache);
_ = &initial_seed;
try w.writeAll("<section");
try rt.attribute(w, arena, "data-p-store", .{ .string = "Helpers_5a3e8e8ffcf6933d" });
if (initial_seed.object.count() > 0) {
var seed_json: std.Io.Writer.Allocating = .init(arena);
try rt.json(&seed_json.writer, arena, initial_seed);
try rt.attribute(w, arena, "data-p", .{ .string = seed_json.written() });
}
try w.writeAll(">");
try w.writeAll("<button");
try w.writeAll(">");
try rt.escape(w, "Replace");
try w.writeAll("</button>");
try w.writeAll("<button");
try w.writeAll(">");
try rt.escape(w, "Hide");
try w.writeAll("</button>");
try w.writeAll("<!--p:when-->");
if (rt.truthy(v2)) {
try w.writeAll("<!--p:fragment-->");
try w.writeAll("<p");
try w.writeAll(">");
try w.writeAll("<!--p:insert-->");
try rt.text(w, arena, try rt.get(v2, "name"));
try w.writeAll("<!--/p:insert-->");
try w.writeAll("</p>");
try w.writeAll("<!--/p:fragment-->");
} else {
try w.writeAll("<p");
try w.writeAll(">");
try rt.escape(w, "Signed out");
try w.writeAll("</p>");
}
try w.writeAll("<!--/p:when-->");
try w.writeAll("<ul");
try w.writeAll(">");
const v8 = try rt.optionalItems(v5);
try w.writeAll("<!--p:when-->");
if (v8.len > 0) {
try w.writeAll("<!--p:list-->");
var v12: std.StringHashMap(void) = .init(arena);
for (v8, 0..) |v9, v10| {
_ = &v9; _ = &v10;
const v11: V = try rt.get(v9, "id");
try rt.uniqueKey(arena, &v12, v11);
try rt.row(w, arena, v11, false);
const v13: V = try rt.get(v9, "name"); _ = &v13;
const v14: V = V{ .float = 0 }; _ = &v14;
try w.writeAll("<li");
try rt.attribute(w, arena, "data-snapshot", v13);
try rt.attribute(w, arena, "data-clicks", v14);
try w.writeAll(">");
try w.writeAll("<!--p:insert-->");
try rt.text(w, arena, try rt.binary(arena, "+", V{ .integer = @intCast(v10) }, V{ .float = 1 }));
try w.writeAll("<!--/p:insert-->");
try rt.escape(w, ". ");
try w.writeAll("<!--p:insert-->");
try rt.text(w, arena, try rt.get(v9, "name"));
try w.writeAll("<!--/p:insert-->");
try w.writeAll("</li>");
try rt.row(w, arena, v11, true);
}
try w.writeAll("<!--/p:list-->");
} else {
try w.writeAll("<li");
try w.writeAll(">");
try rt.escape(w, "Empty");
try w.writeAll("</li>");
}
try w.writeAll("<!--/p:when-->");
try w.writeAll("</ul>");
try w.writeAll("<ol");
try w.writeAll(">");
const v15 = try rt.window(v3, try rt.math("max", &.{V{ .float = 0 },try rt.math("min", &.{V{ .float = 2 },try rt.binary(arena, "-", try rt.get(v1, "length"), v3)})}));
try w.writeAll("<!--p:list-->");
for (v15[0]..v15[1]) |v17| {
const v18: V = .{ .integer = @intCast(v17) };
try rt.row(w, arena, v18, false);
try w.writeAll("<li");
try w.writeAll(">");
try w.writeAll("<!--p:insert-->");
try rt.text(w, arena, try rt.get(try rt.indexed(arena, v1, v18), "name"));
try w.writeAll("<!--/p:insert-->");
try w.writeAll("</li>");
try rt.row(w, arena, v18, true);
}
try w.writeAll("<!--/p:list-->");
try w.writeAll("</ol>");
try w.writeAll("<!--p:when-->");
if (rt.truthy(v2)) {
try w.writeAll("<!--p:fragment-->");
try w.writeAll("<b");
try w.writeAll(">");
try w.writeAll("<!--p:insert-->");
try rt.text(w, arena, try rt.get(v2, "name"));
try w.writeAll("<!--/p:insert-->");
try w.writeAll("</b>");
try w.writeAll("<!--/p:fragment-->");
} else if (rt.truthy(try rt.binary(arena, "===", v4, V{ .string = "missing" }))) {
try w.writeAll("<!--p:fragment-->");
try w.writeAll("<b");
try w.writeAll(">");
try rt.escape(w, "Missing");
try w.writeAll("</b>");
try w.writeAll("<!--/p:fragment-->");
} else {
try w.writeAll("<b");
try w.writeAll(">");
try rt.escape(w, "No match");
try w.writeAll("</b>");
}
try w.writeAll("<!--/p:when-->");
try w.writeAll("</section>");
}
pub const operations = [_]struct { path: []const u8, module: []const u8, name: []const u8 }{
};
pub fn dispatch(w: *std.Io.Writer, arena: std.mem.Allocator, ctx: anytype, path: []const u8, arguments: V) !bool {
_ = &w; _ = &arena; _ = &ctx; _ = &path; _ = &arguments;
return false;
}
pub fn writeTypes(w: *std.Io.Writer, module: []const u8) !bool {
_ = &w; _ = &module;
return false;
}
