// Generated by PJSX. Native imports keep their authored relative paths.
const std = @import("std");
const rt = @import("compiled_runtime");
const V = rt.Value;
pub fn render(w: *std.Io.Writer, arena: std.mem.Allocator, ctx: anytype, props: V, instance_id: []const u8) !void {
_ = &ctx; _ = &instance_id; try rt.validate(props);
const v1: V = try rt.array(arena, &.{try rt.object(arena, &.{"id","name"}, &.{V{ .float = 1 },V{ .string = "One" }})}); _ = &v1;
const initial_values = try rt.object(arena, &.{}, &.{});
const initial_cache = try rt.object(arena, &.{}, &.{});
const initial_seed = try rt.componentSeed(arena, initial_values, props, initial_cache);
_ = &initial_seed;
try w.writeAll("<template data-p-root-start");
try rt.attribute(w, arena, "data-p-store", .{ .string = "HelperRoot_e6bc7a70b92b369f" });
if (initial_seed.object.count() > 0) {
var seed_json: std.Io.Writer.Allocating = .init(arena);
try rt.json(&seed_json.writer, arena, initial_seed);
try rt.attribute(w, arena, "data-p", .{ .string = seed_json.written() });
}
try w.writeAll("></template>");
const v2 = try rt.optionalItems(v1);
try w.writeAll("<!--p:when-->");
if (v2.len > 0) {
try w.writeAll("<!--p:list-->");
var v6: std.StringHashMap(void) = .init(arena);
for (v2, 0..) |v3, v4| {
_ = &v3; _ = &v4;
const v5: V = try rt.get(v3, "id");
try rt.uniqueKey(arena, &v6, v5);
try rt.row(w, arena, v5, false);
try w.writeAll("<tr");
try w.writeAll(">");
try w.writeAll("<td");
try w.writeAll(">");
try w.writeAll("<!--p:insert-->");
try rt.text(w, arena, try rt.get(v3, "name"));
try w.writeAll("<!--/p:insert-->");
try w.writeAll("</td>");
try w.writeAll("<td");
try w.writeAll(">");
try w.writeAll("<button");
try w.writeAll(">");
try rt.escape(w, "Add");
try w.writeAll("</button>");
try w.writeAll("</td>");
try w.writeAll("</tr>");
try rt.row(w, arena, v5, true);
}
try w.writeAll("<!--/p:list-->");
}
try w.writeAll("<!--/p:when-->");
try w.writeAll("<template");
try w.writeAll(" data-p-root-end");
try w.writeAll("></template>");
}
pub const operations = [_]struct { path: []const u8, module: []const u8, name: []const u8 }{
};
pub fn dispatch(w: *std.Io.Writer, arena: std.mem.Allocator, ctx: anytype, path: []const u8, arguments: V) !bool {
_ = &w; _ = &arena; _ = &ctx; _ = &path; _ = &arguments;
return false;
}
pub fn writeTypes(w: *std.Io.Writer, module: []const u8) !bool {
_ = &w; _ = &module;
return false;
}
