// Generated by PJSX. Native imports keep their authored relative paths.
const std = @import("std");
const rt = @import("compiled_runtime");
const V = rt.Value;
pub fn render(w: *std.Io.Writer, arena: std.mem.Allocator, ctx: anytype, props: V, instance_id: []const u8) !void {
_ = &ctx; _ = &instance_id; try rt.validate(props);
const v1: V = try rt.get(props, "search"); _ = &v1;
const v3 = try rt.nativeResult(@import("./backend/users.zig").fetchUsers, ctx, arena, &.{v1});
const v2: V = v3.value; _ = &v2;
const initial_values = try rt.object(arena, &.{"users"}, &.{v2});
const initial_cache = try rt.object(arena, &.{"users"}, &.{try rt.transferCache(arena, ctx, v3.policy, try rt.array(arena, &.{V{ .string = "/_publr/22b2f5af1f2581b3/fetchUsers" }, try rt.array(arena, &.{v1})}), V.null)});
const initial_seed = try rt.componentSeed(arena, initial_values, props, initial_cache);
_ = &initial_seed;
try w.writeAll("<section");
try rt.attribute(w, arena, "aria-busy", V{ .bool = false });
try rt.attribute(w, arena, "data-p-store", .{ .string = "Users_faf761d4bebc0585" });
if (initial_seed.object.count() > 0) {
var seed_json: std.Io.Writer.Allocating = .init(arena);
try rt.json(&seed_json.writer, arena, initial_seed);
try rt.attribute(w, arena, "data-p", .{ .string = seed_json.written() });
}
try w.writeAll(">");
try w.writeAll("<input");
try rt.attribute(w, arena, "value", v1);
try w.writeAll(">");
try w.writeAll("<!--p:loading-->");
try w.writeAll("<ul");
try w.writeAll(">");
try w.writeAll("<!--p:list-->");
for (try rt.items(v2)) |v4| {
try rt.row(w, arena, try rt.get(v4, "id"), false);
try w.writeAll("<li");
try w.writeAll(">");
try w.writeAll("<input");
try w.writeAll(">");
try w.writeAll("<!--p:insert-->");
try rt.text(w, arena, try rt.get(v4, "name"));
try w.writeAll("<!--/p:insert-->");
try w.writeAll("</li>");
try rt.row(w, arena, try rt.get(v4, "id"), true);
}
try w.writeAll("<!--/p:list-->");
try w.writeAll("</ul>");
try w.writeAll("<!--/p:loading-->");
try w.writeAll("</section>");
}
pub const operations = [_]struct { path: []const u8, module: []const u8, name: []const u8 }{
.{ .path = "/_publr/22b2f5af1f2581b3/fetchUsers", .module = "./backend/users.zig", .name = "fetchUsers" },
};
pub fn dispatch(w: *std.Io.Writer, arena: std.mem.Allocator, ctx: anytype, path: []const u8, arguments: V) !bool {
_ = &w; _ = &arena; _ = &ctx; _ = &path; _ = &arguments;
if (std.mem.eql(u8, path, "/_publr/22b2f5af1f2581b3/fetchUsers")) {
const result = try rt.nativeResult(@import("./backend/users.zig").fetchUsers, ctx, arena, try rt.items(arguments));
try rt.publishPolicy(ctx, result.policy);
try rt.json(w, arena, result.value);
return true;
}
return false;
}
pub fn writeTypes(w: *std.Io.Writer, module: []const u8) !bool {
_ = &w; _ = &module;
if (std.mem.eql(u8, module, "./backend/users.zig")) {
try rt.types(w, @import("./backend/users.zig").fetchUsers, "fetchUsers");
return true;
}
return false;
}
