export const pages = {
  index: "IndexPage",
  failure: "FailurePage",
  composition: "CompositionPage",
  props: "PropsPage",
  inputs: "InputsPage",
  reuse: "ReusePage",
  lists: "ListsPage",
  interaction: "InteractionPage",
  portals: "PortalsPage",
  learn: "LearnPage",
  cleanup: "CleanupPage",
  position: "PositionPage",
  awaited: "AwaitedPage",
  effects: "EffectsPage",
  query: "QueryPage",
  refs: "RefsPage",
  derived: "DerivedPage",
  state: "StatePage",
  focus: "FocusPage",
  introduction: "IntroductionPage",
  "shared-state": "SharedStatePage",
  conditional: "ConditionalPage",
  switch: "SwitchPage",
};
