// Generated by PJSX. Native imports keep their authored relative paths.
const std = @import("std");
const rt = @import("compiled_runtime");
const V = rt.Value;
pub fn render(w: *std.Io.Writer, arena: std.mem.Allocator, ctx: anytype, props: V, instance_id: []const u8) !void {
_ = &ctx; _ = &instance_id; try rt.validate(props);
const v1: V = V{ .bool = false }; _ = &v1;
const initial_values = try rt.object(arena, &.{}, &.{});
const initial_cache = try rt.object(arena, &.{}, &.{});
const initial_seed = try rt.componentSeed(arena, initial_values, props, initial_cache);
_ = &initial_seed;
try w.writeAll("<section");
try rt.attribute(w, arena, "data-p-on", .{ .string = "resize.window:toggle" });
try rt.attribute(w, arena, "data-p-bind", .{ .string = "class:$p142_class" });
try rt.attribute(w, arena, "class", try rt.className(arena, try rt.array(arena, &.{V{ .string = "base" },(if (rt.truthy(v1)) V{ .string = "on" } else V{ .string = "off" })})));
try rt.attribute(w, arena, "data-p-store", .{ .string = "Bindings_c69f6f2645d24bcb" });
if (initial_seed.object.count() > 0) {
var seed_json: std.Io.Writer.Allocating = .init(arena);
try rt.json(&seed_json.writer, arena, initial_seed);
try rt.attribute(w, arena, "data-p", .{ .string = seed_json.written() });
}
try w.writeAll(">");
try w.writeAll("<button");
try rt.attribute(w, arena, "data-p-on", .{ .string = "click:toggle;keydown.enter.prevent:toggle" });
try w.writeAll(">");
try rt.escape(w, "Toggle");
try w.writeAll("</button>");
try w.writeAll("<output");
try rt.attribute(w, arena, "data-p-text", .{ .string = "$v309" });
try w.writeAll(">");
try rt.text(w, arena, (if (rt.truthy(v1)) V{ .string = "yes" } else V{ .string = "no" }));
try w.writeAll("</output>");
try w.writeAll("<!--p:html:346-->");
try w.writeAll("<!--p:when-->");
if (rt.truthy(v1)) {
try w.writeAll("<p");
try rt.attribute(w, arena, "aria-hidden", V{ .bool = false });
try w.writeAll(">");
try rt.escape(w, "On");
try w.writeAll("</p>");
} else {
try w.writeAll("<span");
try w.writeAll(">");
try rt.escape(w, "Off");
try w.writeAll("</span>");
}
try w.writeAll("<!--/p:when-->");
try w.writeAll("<!--/p:html:346-->");
try w.writeAll("</section>");
}
pub const operations = [_]struct { path: []const u8, module: []const u8, name: []const u8 }{
};
pub fn dispatch(w: *std.Io.Writer, arena: std.mem.Allocator, ctx: anytype, path: []const u8, arguments: V) !bool {
_ = &w; _ = &arena; _ = &ctx; _ = &path; _ = &arguments;
return false;
}
pub fn writeTypes(w: *std.Io.Writer, module: []const u8) !bool {
_ = &w; _ = &module;
return false;
}
