// Generated by PJSX. Native imports keep their authored relative paths.
const std = @import("std");
const rt = @import("compiled_runtime");
const V = rt.Value;
pub fn render(w: *std.Io.Writer, arena: std.mem.Allocator, ctx: anytype, props: V, instance_id: []const u8) !void {
_ = &ctx; _ = &instance_id; try rt.validate(props);
const v1: V = try rt.get(props, "initial"); _ = &v1;
const v2: V = v1; _ = &v2;
const v3: V = try rt.binary(arena, "*", v1, V{ .float = 2 }); _ = &v3;
const initial_values = try rt.object(arena, &.{}, &.{});
const initial_cache = try rt.object(arena, &.{}, &.{});
const initial_seed = try rt.componentSeed(arena, initial_values, props, initial_cache);
_ = &initial_seed;
try w.writeAll("<section");
try rt.attribute(w, arena, "data-p-store", .{ .string = "Counter_1565eae217ef514d" });
if (initial_seed.object.count() > 0) {
var seed_json: std.Io.Writer.Allocating = .init(arena);
try rt.json(&seed_json.writer, arena, initial_seed);
try rt.attribute(w, arena, "data-p", .{ .string = seed_json.written() });
}
try w.writeAll(">");
try w.writeAll("<button");
try rt.attribute(w, arena, "data-p-on", .{ .string = "click:increment" });
try w.writeAll(">");
try rt.escape(w, "+");
try w.writeAll("</button>");
try w.writeAll("<output");
try w.writeAll(">");
try w.writeAll("<!--p:html:307-->");
try w.writeAll("<!--p:insert-->");
try rt.text(w, arena, v1);
try w.writeAll("<!--/p:insert-->");
try w.writeAll("<!--/p:html:307-->");
try rt.escape(w, " / ");
try w.writeAll("<!--p:html:317-->");
try w.writeAll("<!--p:insert-->");
try rt.text(w, arena, v3);
try w.writeAll("<!--/p:insert-->");
try w.writeAll("<!--/p:html:317-->");
try rt.escape(w, " / ");
try w.writeAll("<!--p:html:329-->");
try w.writeAll("<!--p:insert-->");
try rt.text(w, arena, v1);
try w.writeAll("<!--/p:insert-->");
try w.writeAll("<!--/p:html:329-->");
try w.writeAll("</output>");
try w.writeAll("</section>");
}
pub const operations = [_]struct { path: []const u8, module: []const u8, name: []const u8 }{
};
pub fn dispatch(w: *std.Io.Writer, arena: std.mem.Allocator, ctx: anytype, path: []const u8, arguments: V) !bool {
_ = &w; _ = &arena; _ = &ctx; _ = &path; _ = &arguments;
return false;
}
pub fn writeTypes(w: *std.Io.Writer, module: []const u8) !bool {
_ = &w; _ = &module;
return false;
}
