// Generated by PJSX. Native imports keep their authored relative paths.
const std = @import("std");
const rt = @import("compiled_runtime");
const V = rt.Value;
pub fn render(w: *std.Io.Writer, arena: std.mem.Allocator, ctx: anytype, props: V, instance_id: []const u8) !void {
_ = &ctx; _ = &instance_id; try rt.validate(props);
const v1: V = V{ .float = 0 }; _ = &v1;
const v2: V = V{ .float = 8 }; _ = &v2;
const initial_values = try rt.object(arena, &.{}, &.{});
const initial_cache = try rt.object(arena, &.{}, &.{});
const initial_seed = try rt.componentSeed(arena, initial_values, props, initial_cache);
_ = &initial_seed;
try w.writeAll("<section");
try rt.attribute(w, arena, "class", try rt.className(arena, try rt.array(arena, &.{V{ .string = "explicit-overlay" }})));
try rt.attribute(w, arena, "data-p-store", .{ .string = "ExplicitOverlay_b028c1b6c715e05a" });
if (initial_seed.object.count() > 0) {
var seed_json: std.Io.Writer.Allocating = .init(arena);
try rt.json(&seed_json.writer, arena, initial_seed);
try rt.attribute(w, arena, "data-p", .{ .string = seed_json.written() });
}
try w.writeAll(">");
try w.writeAll("<button");
try rt.attribute(w, arena, "data-p-anchor", V{ .bool = true });
try w.writeAll(">");
try rt.escape(w, "Decoy");
try w.writeAll("</button>");
try w.writeAll("<button");
try rt.attribute(w, arena, "data-p-ref", .{ .string = "p356_0" });
try w.writeAll(">");
try rt.escape(w, "Anchor");
try w.writeAll("</button>");
try w.writeAll("<aside");
try rt.attribute(w, arena, "data-p-bind", .{ .string = "data-p-portal:$p400_1;data-p-position:$p400_2" });
try rt.attribute(w, arena, "class", try rt.className(arena, try rt.array(arena, &.{V{ .string = "custom" }})));
try rt.attribute(w, arena, "data-p-portal", .{ .bool = true });
try rt.attribute(w, arena, "data-p-position", .{ .bool = true });
try w.writeAll(">");
try w.writeAll("<button");
try rt.attribute(w, arena, "data-p-text", .{ .string = "$v575" });
try rt.attribute(w, arena, "data-p-on", .{ .string = "click:increment" });
try w.writeAll(">");
try rt.text(w, arena, v1);
try w.writeAll("</button>");
try w.writeAll("</aside>");
try w.writeAll("<aside");
try rt.attribute(w, arena, "class", try rt.className(arena, try rt.array(arena, &.{V{ .string = "selector" }})));
try rt.attribute(w, arena, "data-p-portal", V{ .string = "#custom-portal" });
try w.writeAll(">");
try rt.escape(w, "Selector");
try w.writeAll("</aside>");
try w.writeAll("<aside");
try rt.attribute(w, arena, "data-p-bind", .{ .string = "data-p-position:$p684_1" });
try rt.attribute(w, arena, "class", try rt.className(arena, try rt.array(arena, &.{V{ .string = "inline" }})));
try rt.attribute(w, arena, "data-p-position", .{ .bool = true });
try w.writeAll(">");
try rt.escape(w, "Inline");
try w.writeAll("</aside>");
try w.writeAll("<div");
try rt.attribute(w, arena, "data-p-ref", .{ .string = "p791_1" });
try rt.attribute(w, arena, "id", V{ .string = "custom-portal" });
try w.writeAll(">");
try w.writeAll("</div>");
try w.writeAll("</section>");
}
pub const operations = [_]struct { path: []const u8, module: []const u8, name: []const u8 }{
};
pub fn dispatch(w: *std.Io.Writer, arena: std.mem.Allocator, ctx: anytype, path: []const u8, arguments: V) !bool {
_ = &w; _ = &arena; _ = &ctx; _ = &path; _ = &arguments;
return false;
}
pub fn writeTypes(w: *std.Io.Writer, module: []const u8) !bool {
_ = &w; _ = &module;
return false;
}
