// Generated by PJSX. Native imports keep their authored relative paths.
const std = @import("std");
const rt = @import("compiled_runtime");
const V = rt.Value;
pub fn render(w: *std.Io.Writer, arena: std.mem.Allocator, ctx: anytype, props: V, instance_id: []const u8) !void {
_ = &ctx; _ = &instance_id; try rt.validate(props);
const v2 = try rt.nativeResult(@import("./backend/metadata.zig").profile, ctx, arena, &.{});
const v1: V = v2.value; _ = &v1;
const v4 = try rt.nativeResult(@import("./backend/metadata.zig").scalar, ctx, arena, &.{});
const v3: V = v4.value; _ = &v3;
const v5: V = v1; _ = &v5;
const initial_values = try rt.object(arena, &.{"data","number"}, &.{v1,v3});
const initial_cache = try rt.object(arena, &.{"data","number"}, &.{try rt.transferCache(arena, ctx, v2.policy, try rt.array(arena, &.{V{ .string = "/_publr/7a733e59ccb8dd63/profile" }, try rt.array(arena, &.{})}), try rt.object(arena, &.{"ttl","tags"}, &.{V{ .float = 60000 },try rt.array(arena, &.{V{ .string = "profiles" }})})),try rt.transferCache(arena, ctx, v4.policy, try rt.array(arena, &.{V{ .string = "/_publr/50dc0a416f1a2900/scalar" }, try rt.array(arena, &.{})}), V.null)});
const initial_seed = try rt.componentSeed(arena, initial_values, props, initial_cache);
_ = &initial_seed;
try w.writeAll("<section");
try rt.attribute(w, arena, "data-p-bind", .{ .string = "aria-busy:$p386_0;data-error:$p386_1" });
try rt.attribute(w, arena, "aria-busy", V{ .bool = false });
try rt.attribute(w, arena, "data-error", V{ .bool = false });
try rt.attribute(w, arena, "data-p-store", .{ .string = "Metadata_be66011bee42ea22" });
if (initial_seed.object.count() > 0) {
var seed_json: std.Io.Writer.Allocating = .init(arena);
try rt.json(&seed_json.writer, arena, initial_seed);
try rt.attribute(w, arena, "data-p", .{ .string = seed_json.written() });
}
try w.writeAll(">");
try w.writeAll("<button");
try rt.attribute(w, arena, "data-p-on", .{ .string = "click:reload" });
try w.writeAll(">");
try rt.escape(w, "Refresh");
try w.writeAll("</button>");
try w.writeAll("<!--p:html:506-->");
try w.writeAll("<!--p:loading-->");
try w.writeAll("<p");
try w.writeAll(">");
try w.writeAll("<!--p:html:553-->");
try w.writeAll("<!--p:insert-->");
try rt.text(w, arena, try rt.get(v1, "error"));
try w.writeAll("<!--/p:insert-->");
try w.writeAll("<!--/p:html:553-->");
try rt.escape(w, " / ");
try w.writeAll("<!--p:html:577-->");
try w.writeAll("<!--p:insert-->");
try rt.text(w, arena, try rt.get(v1, "isPending"));
try w.writeAll("<!--/p:insert-->");
try w.writeAll("<!--/p:html:577-->");
try rt.escape(w, " / ");
try w.writeAll("<!--p:html:605-->");
try w.writeAll("<!--p:insert-->");
try rt.text(w, arena, try rt.get(v1, "isError"));
try w.writeAll("<!--/p:insert-->");
try w.writeAll("<!--/p:html:605-->");
try w.writeAll("</p>");
try w.writeAll("<span");
try rt.attribute(w, arena, "data-p-text", .{ .string = "$v647" });
try w.writeAll(">");
try rt.text(w, arena, (if (rt.truthy(try rt.binary(arena, "===", v3, V.null))) V{ .string = "null" } else V{ .string = "number" }));
try w.writeAll("</span>");
try w.writeAll("<!--/p:loading-->");
try w.writeAll("<!--/p:html:506-->");
try w.writeAll("<b");
try rt.attribute(w, arena, "data-p-bind", .{ .string = "aria-busy:$p724_0;data-error:$p724_1" });
try rt.attribute(w, arena, "aria-busy", V{ .bool = false });
try rt.attribute(w, arena, "data-error", V{ .bool = false });
try w.writeAll(">");
try rt.escape(w, "Metadata");
try w.writeAll("</b>");
try w.writeAll("</section>");
}
pub const operations = [_]struct { path: []const u8, module: []const u8, name: []const u8 }{
.{ .path = "/_publr/7a733e59ccb8dd63/profile", .module = "./backend/metadata.zig", .name = "profile" },
.{ .path = "/_publr/50dc0a416f1a2900/scalar", .module = "./backend/metadata.zig", .name = "scalar" },
};
pub fn dispatch(w: *std.Io.Writer, arena: std.mem.Allocator, ctx: anytype, path: []const u8, arguments: V) !bool {
_ = &w; _ = &arena; _ = &ctx; _ = &path; _ = &arguments;
if (std.mem.eql(u8, path, "/_publr/7a733e59ccb8dd63/profile")) {
const result = try rt.nativeResult(@import("./backend/metadata.zig").profile, ctx, arena, try rt.items(arguments));
try rt.publishPolicy(ctx, result.policy);
try rt.json(w, arena, result.value);
return true;
}
if (std.mem.eql(u8, path, "/_publr/50dc0a416f1a2900/scalar")) {
const result = try rt.nativeResult(@import("./backend/metadata.zig").scalar, ctx, arena, try rt.items(arguments));
try rt.publishPolicy(ctx, result.policy);
try rt.json(w, arena, result.value);
return true;
}
return false;
}
pub fn writeTypes(w: *std.Io.Writer, module: []const u8) !bool {
_ = &w; _ = &module;
if (std.mem.eql(u8, module, "./backend/metadata.zig")) {
try rt.types(w, @import("./backend/metadata.zig").profile, "profile");
try rt.types(w, @import("./backend/metadata.zig").scalar, "scalar");
return true;
}
return false;
}
