// Generated by PJSX. Native imports keep their authored relative paths.
const std = @import("std");
const rt = @import("compiled_runtime");
const V = rt.Value;
pub fn render(w: *std.Io.Writer, arena: std.mem.Allocator, ctx: anytype, props: V, instance_id: []const u8) !void {
_ = &ctx; _ = &instance_id; try rt.validate(props);
const initial_values = try rt.object(arena, &.{}, &.{});
const initial_cache = try rt.object(arena, &.{}, &.{});
const initial_seed = try rt.componentSeed(arena, initial_values, props, initial_cache);
_ = &initial_seed;
try w.writeAll("<div");
try rt.attribute(w, arena, "class", V{ .string = "static-shell" });
try w.writeAll(">");
try w.writeAll("<p");
try w.writeAll(">");
try rt.escape(w, "Fixed ");
try w.writeAll("<!--p:html:132-->");
try rt.text(w, arena, V{ .float = 7 });
try w.writeAll("<!--/p:html:132-->");
try w.writeAll("</p>");
try w.writeAll("<!--p:html:146-->");
try @import("./Counter.zig").render(w, arena, ctx, try rt.object(arena, &.{"initial"}, &.{V{ .float = 1 }}), try std.fmt.allocPrint(arena, "{s}/v1", .{instance_id}));
try w.writeAll("<!--/p:html:146-->");
try w.writeAll("<!--p:html:176-->");
try @import("./Counter.zig").render(w, arena, ctx, try rt.object(arena, &.{"initial"}, &.{V{ .float = 5 }}), try std.fmt.allocPrint(arena, "{s}/v2", .{instance_id}));
try w.writeAll("<!--/p:html:176-->");
try w.writeAll("</div>");
}
pub const operations = [_]struct { path: []const u8, module: []const u8, name: []const u8 }{
};
pub fn dispatch(w: *std.Io.Writer, arena: std.mem.Allocator, ctx: anytype, path: []const u8, arguments: V) !bool {
_ = &w; _ = &arena; _ = &ctx; _ = &path; _ = &arguments;
return false;
}
pub fn writeTypes(w: *std.Io.Writer, module: []const u8) !bool {
_ = &w; _ = &module;
return false;
}
