// Generated by PJSX. Native imports keep their authored relative paths.
const std = @import("std");
const rt = @import("compiled_runtime");
const V = rt.Value;
pub fn render(w: *std.Io.Writer, arena: std.mem.Allocator, ctx: anytype, props: V, instance_id: []const u8) !void {
_ = &ctx; _ = &instance_id; try rt.validate(props);
const v1: V = V{ .float = 0 }; _ = &v1;
const initial_values = try rt.object(arena, &.{}, &.{});
const initial_cache = try rt.object(arena, &.{}, &.{});
const initial_seed = try rt.componentSeed(arena, initial_values, props, initial_cache);
_ = &initial_seed;
try w.writeAll("<tr");
try rt.attribute(w, arena, "data-p-store", .{ .string = "TableRow_ef31a74dee07af52" });
if (initial_seed.object.count() > 0) {
var seed_json: std.Io.Writer.Allocating = .init(arena);
try rt.json(&seed_json.writer, arena, initial_seed);
try rt.attribute(w, arena, "data-p", .{ .string = seed_json.written() });
}
try w.writeAll(">");
try w.writeAll("<td");
try w.writeAll(">");
try w.writeAll("<button");
try rt.attribute(w, arena, "data-p-on", .{ .string = "click:increment" });
try w.writeAll(">");
try rt.escape(w, "+");
try w.writeAll("</button>");
try w.writeAll("</td>");
try w.writeAll("<td");
try rt.attribute(w, arena, "data-p-text", .{ .string = "$v184" });
try w.writeAll(">");
try rt.text(w, arena, v1);
try w.writeAll("</td>");
try w.writeAll("</tr>");
}
pub const operations = [_]struct { path: []const u8, module: []const u8, name: []const u8 }{
};
pub fn dispatch(w: *std.Io.Writer, arena: std.mem.Allocator, ctx: anytype, path: []const u8, arguments: V) !bool {
_ = &w; _ = &arena; _ = &ctx; _ = &path; _ = &arguments;
return false;
}
pub fn writeTypes(w: *std.Io.Writer, module: []const u8) !bool {
_ = &w; _ = &module;
return false;
}
