export type Chapter = {
  title: string;
  description: string;
  heading: string;
  source: string;
  bodyClass: string;
  styles: string[];
  tryIt: string;
  noscript: string;
  previous: string;
  next: string;
  command: string;
};

export const chapters: Record<string, Chapter> = {
  failure: {
    title: "Keep the result while you wait · Publr",
    description:
      "Keep previous people visible after a failed read, retry, and let the latest search win.",
    heading: "Recover from a failed request.",
    source: "ResilientSearch.ptsx",
    bodyClass: "interaction-lesson awaited-lesson failure-lesson",
    styles: ["/introduction.css", "/awaited.css"],
    tryIt:
      "Enable Fail next request, then search for Ada. Retry keeps the same search. For overlapping searches, enable Slow next request, search for Elena, then search for Jules.",
    noscript: "The server list is ready. JavaScript enables searching and the walkthroughs.",
    previous: "/learn/awaited",
    next: "/learn/query",
    command: "failure",
  },
  composition: {
    title: "Compose a page · Publr",
    description:
      "An effect starts a timer. Its cleanup stops the timer when the component is removed.",
    heading: "Compose a page.",
    source: "StaticPage.ptsx",
    bodyClass: "interaction-lesson",
    styles: ["/introduction.css"],
    tryIt: "Two components. One rendered greeting.",
    noscript: "JavaScript is required for both click handlers and the walkthroughs.",
    previous: "/learn/cleanup",
    next: "",
    command: "composition",
  },
  props: {
    title: "Pass it to a child · Publr",
    description: "A parent passes its changing name to a child through typed props.",
    heading: "Pass it to a child.",
    source: "PropsDemo.ptsx",
    bodyClass: "interaction-lesson",
    styles: ["/introduction.css"],
    tryIt: "Type a name. The parent passes it to the greeting.",
    noscript: "JavaScript is required for both click handlers and the walkthroughs.",
    previous: "/learn/composition",
    next: "/learn/reuse",
    command: "props",
  },
  inputs: {
    title: "Type it. See it change · Publr",
    description:
      "Connect a text input to state. Typing and resetting update the input and greeting.",
    heading: "Type it. See it change.",
    source: "NameInput.ptsx",
    bodyClass: "interaction-lesson",
    styles: ["/introduction.css"],
    tryIt: "Type your name. Then reset it. The input and greeting stay in sync.",
    noscript: "JavaScript is required for both click handlers and the walkthroughs.",
    previous: "/learn/lists",
    next: "/learn/switch",
    command: "inputs",
  },
  reuse: {
    title: "Same component. Separate state · Publr",
    description: "Two copies of one counter start with different props and keep their own state.",
    heading: "Same component. Separate state.",
    source: "ReuseDemo.ptsx",
    bodyClass: "interaction-lesson",
    styles: ["/introduction.css"],
    tryIt: "Start at 0 and 10. Increment either counter. The other keeps its count.",
    noscript: "JavaScript is required for both click handlers and the walkthroughs.",
    previous: "/learn/props",
    next: "/learn/awaited",
    command: "reuse",
  },
  lists: {
    title: "One item. One row · Publr",
    description: "For renders a row for each item. Add and remove items in both rendering targets.",
    heading: "One item. One row.",
    source: "ItemList.ptsx",
    bodyClass: "interaction-lesson",
    styles: ["/introduction.css"],
    tryIt: "Add an item, then remove it. The other rows stay in place.",
    noscript: "JavaScript is required for both click handlers and the walkthroughs.",
    previous: "/learn/conditional",
    next: "/learn/inputs",
    command: "lists",
  },
  interaction: {
    title: "Now add a click · Publr",
    description:
      "Add a click handler to one component. It works with server-rendered HTML and browser-created DOM.",
    heading: "Now add a click.",
    source: "Hello.ptsx",
    bodyClass: "interaction-lesson",
    styles: ["/introduction.css"],
    tryIt: "Click either button. Both run the same code.",
    noscript: "JavaScript is required for both click handlers and the walkthroughs.",
    previous: "/learn/introduction",
    next: "/learn/state",
    command: "hello",
  },
  portals: {
    title: "Outside the box. Still connected · Publr",
    description:
      "Move a details panel outside a clipping container while keeping its state and events connected.",
    heading: "Outside the box. Still connected.",
    source: "PersonDetails.ptsx",
    bodyClass: "interaction-lesson portals-lesson",
    styles: ["/introduction.css", "/portals.css"],
    tryIt:
      "Open details. The panel escapes the dashed container. Thank Ada from the panel: the count inside the container still updates.",
    noscript:
      "The server renders Ada’s card. JavaScript enables the details panel and walkthroughs.",
    previous: "/learn/query",
    next: "/learn/position",
    command: "portals",
  },
  cleanup: {
    title: "Stop when it leaves · Publr",
    description:
      "An effect starts a timer. Its cleanup stops the timer when the component is removed.",
    heading: "Stop when it leaves.",
    source: "TimerDemo.ptsx",
    bodyClass: "interaction-lesson",
    styles: ["/introduction.css"],
    tryIt: "Remove the timer, then show it again. A new timer starts at zero.",
    noscript: "JavaScript is required for both click handlers and the walkthroughs.",
    previous: "/learn/refs",
    next: "",
    command: "cleanup",
  },
  position: {
    title: "Keep it by the button · Publr",
    description:
      "Keep a details panel anchored to its trigger as it scrolls, flips, and stays inside the viewport.",
    heading: "Keep it by the button.",
    source: "AnchoredDetails.ptsx",
    bodyClass: "interaction-lesson portals-lesson position-lesson",
    styles: ["/introduction.css", "/portals.css", "/position.css"],
    tryIt:
      "Open details, then move the trigger to the bottom or right edge. Scroll the scene: the panel follows its button and changes placement when it needs room.",
    noscript:
      "The server renders Ada’s card. JavaScript enables the details panel and walkthroughs.",
    previous: "/learn/portals",
    next: "/learn/focus",
    command: "position",
  },
  awaited: {
    title: "Keep the result while you wait · Publr",
    description:
      "Fetch people from a local API. Keep the previous result visible while a new search waits.",
    heading: "Keep the result while you wait.",
    source: "PeopleSearch.ptsx",
    bodyClass: "interaction-lesson awaited-lesson",
    styles: ["/introduction.css", "/awaited.css"],
    tryIt: "Search for Ada. The API takes 800 ms; the previous people stay visible while you wait.",
    noscript: "The server list is ready. JavaScript enables searching and the walkthroughs.",
    previous: "/learn/reuse",
    next: "/learn/failure",
    command: "awaited",
  },
  effects: {
    title: "Do something when a value changes · Publr",
    description: "An effect keeps the browser tab title in sync with count.",
    heading: "Do something when a value changes.",
    source: "EffectCounter.ptsx",
    bodyClass: "interaction-lesson",
    styles: ["/introduction.css"],
    tryIt: "Click Increment. Watch the title above each preview change.",
    noscript: "JavaScript is required for both click handlers and the walkthroughs.",
    previous: "/learn/derived",
    next: "/learn/conditional",
    command: "effects",
  },
  query: {
    title: "Two readers. One request · Publr",
    description:
      "Share a request between two readers, reuse fresh results, and refresh them by tag.",
    heading: "Two readers. One request.",
    source: "SharedPeople.ptsx",
    bodyClass: "interaction-lesson awaited-lesson query-lesson",
    styles: ["/introduction.css", "/awaited.css"],
    tryIt:
      "Choose Ada, then All people to reuse a fresh result. Add person and invalidate saves a new person on the server, then both readers fetch the updated list through one shared request.",
    noscript: "The server list is ready. JavaScript enables searching and the walkthroughs.",
    previous: "/learn/failure",
    next: "/learn/portals",
    command: "query",
  },
  refs: {
    title: "Reach the actual element · Publr",
    description: "Use ref to access a rendered input and focus it from a button.",
    heading: "Reach the actual element.",
    source: "FocusInput.ptsx",
    bodyClass: "interaction-lesson",
    styles: ["/introduction.css"],
    tryIt: "Click Focus input. The cursor moves into that input.",
    noscript: "JavaScript is required for both click handlers and the walkthroughs.",
    previous: "/learn/switch",
    next: "/learn/cleanup",
    command: "refs",
  },
  derived: {
    title: "One value follows another · Publr",
    description: "Change count. A derived value keeps doubled up to date in both targets.",
    heading: "One value follows another.",
    source: "DerivedCounter.ptsx",
    bodyClass: "interaction-lesson",
    styles: ["/introduction.css"],
    tryIt: "Click Increment. Count goes up by 1. Doubled goes up by 2.",
    noscript: "JavaScript is required for both click handlers and the walkthroughs.",
    previous: "/learn/shared-state",
    next: "/learn/effects",
    command: "derived",
  },
  state: {
    title: "Now change a value · Publr",
    description:
      "One counter, rendered on the server or in the browser. State keeps the displayed count up to date.",
    heading: "Now change a value.",
    source: "StateCounter.ptsx",
    bodyClass: "interaction-lesson",
    styles: ["/introduction.css"],
    tryIt: "Click Increment. Each counter keeps its own count.",
    noscript: "JavaScript is required for both click handlers and the walkthroughs.",
    previous: "/learn/interaction",
    next: "/learn/shared-state",
    command: "state",
  },
  focus: {
    title: "Keep focus in the dialog · Publr",
    description: "Move focus into a dialog, keep Tab inside, and return focus when it closes.",
    heading: "Keep focus in the dialog.",
    source: "FocusDetails.ptsx",
    bodyClass: "interaction-lesson portals-lesson focus-lesson",
    styles: ["/introduction.css", "/portals.css", "/focus.css"],
    tryIt:
      "Open details, then press Tab and Shift+Tab. Focus stays in the dialog. Press Escape or Close details to restore the previously focused element.",
    noscript:
      "The server renders Ada’s card. JavaScript enables the details panel and walkthroughs.",
    previous: "/learn/position",
    next: "",
    command: "focus",
  },
  introduction: {
    title: "One component, two rendering paths · Publr",
    description: "One PTSX component, rendered on the server or in the browser.",
    heading: "One component, two rendering paths.",
    source: "TemplateGreeting.ptsx",
    bodyClass: "interaction-lesson",
    styles: ["/introduction.css"],
    tryIt: "Both paths render the same greeting.",
    noscript: "",
    previous: "",
    next: "/learn/interaction",
    command: "greeting",
  },
  conditional: {
    title: "Show it when you need it · Publr",
    description: "A condition adds or removes a message in both rendering targets.",
    heading: "Show it when you need it.",
    source: "ConditionalMessage.ptsx",
    bodyClass: "interaction-lesson",
    styles: ["/introduction.css"],
    tryIt: "Click Toggle message to remove the message, then bring it back.",
    noscript: "JavaScript is required for both click handlers and the walkthroughs.",
    previous: "/learn/effects",
    next: "/learn/lists",
    command: "conditional",
  },
  switch: {
    title: "One match at a time · Publr",
    description:
      "Switch selects the first matching case. When none match, it renders the fallback.",
    heading: "One match at a time.",
    source: "StatusMessage.ptsx",
    bodyClass: "interaction-lesson",
    styles: ["/introduction.css"],
    tryIt: "Choose Ready, Busy, or Other. Only one message appears.",
    noscript: "JavaScript is required for both click handlers and the walkthroughs.",
    previous: "/learn/inputs",
    next: "/learn/refs",
    command: "switch",
  },
};
