import { mount } from "publr/dom";
// @ts-expect-error Generated by PJSX.
import { AsyncExample } from "../.generated/components/AsyncExample.js";

export function start(host: HTMLElement) {
  mount(host, AsyncExample);
  return "Mounted. Search calls fetchMembers through its generated native endpoint.";
}
