import { mount } from "publr/dom";
// @ts-expect-error Generated by PJSX.
import { SimpleCounter } from "../.generated/components/SimpleCounter.js";

export function start(host: HTMLElement) {
  mount(host, SimpleCounter);
  return "Mounted. The browser created the counter inside the empty host.";
}
