import { mount } from "publr/dom";
// @ts-expect-error Generated by PJSX.
import { QueryExample } from "../.generated/components/QueryExample.js";

export function start(host: HTMLElement) {
  mount(host, QueryExample);
  return "Mounted. Two readers share one request. Watch Requests when invalidating.";
}
